// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnnualRecord struct {
	ID                     int32              `json:"id"`
	UserID                 int32              `json:"userId"`
	Year                   int32              `json:"year"`
	QuotaPlanID            pgtype.Int4        `json:"quotaPlanId"`
	RolloverVacationDay    pgtype.Numeric     `json:"rolloverVacationDay"`
	UsedVacationDay        pgtype.Numeric     `json:"usedVacationDay"`
	UsedSickLeaveDay       pgtype.Numeric     `json:"usedSickLeaveDay"`
	WorkedOnHolidayDay     pgtype.Numeric     `json:"workedOnHolidayDay"`
	WorkedDay              pgtype.Numeric     `json:"workedDay"`
	UsedMedicalExpenseBaht pgtype.Numeric     `json:"usedMedicalExpenseBaht"`
	CreatedAt              pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt              pgtype.Timestamptz `json:"updatedAt"`
}

type Holiday struct {
	ID        int32              `json:"id"`
	Date      pgtype.Date        `json:"date"`
	Name      string             `json:"name"`
	Note      pgtype.Text        `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type LeaveLog struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"userId"`
	Type      string             `json:"type"`
	Date      pgtype.Date        `json:"date"`
	Note      pgtype.Text        `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type MedicalExpense struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"userId"`
	Amount      pgtype.Numeric     `json:"amount"`
	ReceiptName pgtype.Text        `json:"receiptName"`
	ReceiptDate pgtype.Date        `json:"receiptDate"`
	Note        pgtype.Text        `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type QuotaPlan struct {
	ID                      int32              `json:"id"`
	PlanName                string             `json:"planName"`
	Year                    int32              `json:"year"`
	QuotaVacationDay        pgtype.Numeric     `json:"quotaVacationDay"`
	QuotaMedicalExpenseBaht pgtype.Numeric     `json:"quotaMedicalExpenseBaht"`
	CreatedByUserID         pgtype.Int4        `json:"createdByUserId"`
	CreatedAt               pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt               pgtype.Timestamptz `json:"updatedAt"`
}

type Task struct {
	ID             int32              `json:"id"`
	Url            pgtype.Text        `json:"url"`
	TaskCategoryID pgtype.Int4        `json:"taskCategoryId"`
	Note           pgtype.Text        `json:"note"`
	Title          pgtype.Text        `json:"title"`
	Status         pgtype.Text        `json:"status"`
	StatusColor    pgtype.Text        `json:"statusColor"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type TaskCategory struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	ParentID    pgtype.Int4        `json:"parentId"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type TaskEstimate struct {
	ID              int32              `json:"id"`
	TaskID          int32              `json:"taskId"`
	EstimateDay     pgtype.Numeric     `json:"estimateDay"`
	Note            pgtype.Text        `json:"note"`
	CreatedByUserID int32              `json:"createdByUserId"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type TaskLog struct {
	ID              int32              `json:"id"`
	TaskID          int32              `json:"taskId"`
	WorkedDay       pgtype.Numeric     `json:"workedDay"`
	CreatedByUserID int32              `json:"createdByUserId"`
	WorkedDate      pgtype.Date        `json:"workedDate"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	IsWorkOnHoliday pgtype.Bool        `json:"isWorkOnHoliday"`
}

type User struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	UserType  string             `json:"userType"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}
