// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Update existing records
	AssignQuotaPlanToAllUsers(ctx context.Context, arg AssignQuotaPlanToAllUsersParams) error
	CreateAnnualRecord(ctx context.Context, arg CreateAnnualRecordParams) (AnnualRecord, error)
	CreateHoliday(ctx context.Context, arg CreateHolidayParams) (Holiday, error)
	CreateLeaveLog(ctx context.Context, arg CreateLeaveLogParams) (LeaveLog, error)
	CreateMedicalExpense(ctx context.Context, arg CreateMedicalExpenseParams) (MedicalExpense, error)
	CreateNextYearAnnualRecords(ctx context.Context, arg CreateNextYearAnnualRecordsParams) ([]AnnualRecord, error)
	CreateQuotaPlan(ctx context.Context, arg CreateQuotaPlanParams) (QuotaPlan, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTaskCategory(ctx context.Context, arg CreateTaskCategoryParams) (TaskCategory, error)
	CreateTaskEstimate(ctx context.Context, arg CreateTaskEstimateParams) (TaskEstimate, error)
	CreateTaskLog(ctx context.Context, arg CreateTaskLogParams) (TaskLog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAnnualRecord(ctx context.Context, id int32) error
	DeleteHoliday(ctx context.Context, id int32) error
	DeleteLeaveLog(ctx context.Context, id int32) error
	DeleteMedicalExpense(ctx context.Context, id int32) error
	DeleteQuotaPlan(ctx context.Context, id int32) error
	DeleteTask(ctx context.Context, id int32) error
	DeleteTaskCategory(ctx context.Context, id int32) error
	DeleteTaskEstimate(ctx context.Context, id int32) error
	DeleteTaskLog(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAnnualRecord(ctx context.Context, id int32) (AnnualRecord, error)
	GetAnnualRecordByUserAndYear(ctx context.Context, arg GetAnnualRecordByUserAndYearParams) (GetAnnualRecordByUserAndYearRow, error)
	GetHoliday(ctx context.Context, id int32) (Holiday, error)
	GetHolidayByDate(ctx context.Context, date pgtype.Date) (Holiday, error)
	GetLeaveLog(ctx context.Context, id int32) (LeaveLog, error)
	GetMedicalExpense(ctx context.Context, id int32) (MedicalExpense, error)
	GetQuotaPlan(ctx context.Context, id int32) (QuotaPlan, error)
	GetQuotaPlanByNameAndYear(ctx context.Context, arg GetQuotaPlanByNameAndYearParams) (QuotaPlan, error)
	GetTask(ctx context.Context, id int32) (Task, error)
	GetTaskCategory(ctx context.Context, id int32) (TaskCategory, error)
	GetTaskEstimate(ctx context.Context, id int32) (TaskEstimate, error)
	GetTaskLog(ctx context.Context, id int32) (TaskLog, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAnnualRecordsByUser(ctx context.Context, userID int32) ([]ListAnnualRecordsByUserRow, error)
	ListAnnualRecordsByYear(ctx context.Context, year int32) ([]ListAnnualRecordsByYearRow, error)
	ListHolidays(ctx context.Context, arg ListHolidaysParams) ([]Holiday, error)
	ListHolidaysByYear(ctx context.Context, date pgtype.Date) ([]Holiday, error)
	ListLeaveLogsByDateRange(ctx context.Context, arg ListLeaveLogsByDateRangeParams) ([]LeaveLog, error)
	ListLeaveLogsByType(ctx context.Context, arg ListLeaveLogsByTypeParams) ([]LeaveLog, error)
	ListLeaveLogsByUser(ctx context.Context, arg ListLeaveLogsByUserParams) ([]LeaveLog, error)
	ListLeaveLogsByYear(ctx context.Context, arg ListLeaveLogsByYearParams) ([]LeaveLog, error)
	ListMedicalExpensesByUser(ctx context.Context, arg ListMedicalExpensesByUserParams) ([]MedicalExpense, error)
	ListMedicalExpensesByYear(ctx context.Context, arg ListMedicalExpensesByYearParams) ([]MedicalExpense, error)
	ListQuotaPlans(ctx context.Context) ([]QuotaPlan, error)
	ListQuotaPlansByYear(ctx context.Context, year int32) ([]QuotaPlan, error)
	ListRootTaskCategories(ctx context.Context) ([]TaskCategory, error)
	ListTaskCategories(ctx context.Context, arg ListTaskCategoriesParams) ([]TaskCategory, error)
	ListTaskCategoriesByParent(ctx context.Context, parentID pgtype.Int4) ([]TaskCategory, error)
	ListTaskEstimatesByTask(ctx context.Context, taskID int32) ([]TaskEstimate, error)
	ListTaskEstimatesByUser(ctx context.Context, arg ListTaskEstimatesByUserParams) ([]TaskEstimate, error)
	ListTaskLogsByDateRange(ctx context.Context, arg ListTaskLogsByDateRangeParams) ([]TaskLog, error)
	ListTaskLogsByTask(ctx context.Context, taskID int32) ([]TaskLog, error)
	ListTaskLogsByUser(ctx context.Context, arg ListTaskLogsByUserParams) ([]TaskLog, error)
	ListTaskLogsByUserAndDateRange(ctx context.Context, arg ListTaskLogsByUserAndDateRangeParams) ([]TaskLog, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTasksByCategory(ctx context.Context, taskCategoryID pgtype.Int4) ([]Task, error)
	ListTasksByCategoryWithSubcategories(ctx context.Context, id int32) ([]Task, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateAnnualRecord(ctx context.Context, arg UpdateAnnualRecordParams) (AnnualRecord, error)
	UpdateHoliday(ctx context.Context, arg UpdateHolidayParams) (Holiday, error)
	UpdateLeaveLog(ctx context.Context, arg UpdateLeaveLogParams) (LeaveLog, error)
	UpdateMedicalExpense(ctx context.Context, arg UpdateMedicalExpenseParams) (MedicalExpense, error)
	UpdateQuotaPlan(ctx context.Context, arg UpdateQuotaPlanParams) (QuotaPlan, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskCategory(ctx context.Context, arg UpdateTaskCategoryParams) (TaskCategory, error)
	UpdateTaskEstimate(ctx context.Context, arg UpdateTaskEstimateParams) (TaskEstimate, error)
	UpdateTaskLog(ctx context.Context, arg UpdateTaskLogParams) (TaskLog, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertAnnualRecordForUser(ctx context.Context, arg UpsertAnnualRecordForUserParams) (AnnualRecord, error)
}

var _ Querier = (*Queries)(nil)
